/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.96
 * Generated at: 2024-12-08 17:36:08 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.sg.restaurantpojo.Restaurant;
import com.sg.menupojo.Menu;
import java.util.List;
import com.sg.userpojo.User;

public final class home_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(6);
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("com.sg.restaurantpojo.Restaurant");
    _jspx_imports_classes.add("com.sg.menupojo.Menu");
    _jspx_imports_classes.add("com.sg.userpojo.User");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>Home - Food Application</title>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.6.0/css/fontawesome.min.css\" integrity=\"sha512-B46MVOJpI6RBsdcU307elYeStF2JKT87SsHZfRSkjVi4/iZ3912zXi45X5/CBr/GbCyLx6M1GQtTKYRd52Jxgw==\" crossorigin=\"anonymous\" referrerpolicy=\"no-referrer\" />\r\n");
      out.write("    <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css\" rel=\"stylesheet\" integrity=\"sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH\" crossorigin=\"anonymous\">\r\n");
      out.write("\r\n");
      out.write("    <style>\r\n");
      out.write("        /* Google Font */\r\n");
      out.write("        @import url('https://fonts.googleapis.com/css2?family=Nunito+Sans:wght@400;600;700&display=swap');\r\n");
      out.write("\r\n");
      out.write("        html {\r\n");
      out.write("            scroll-behavior: smooth;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        body {\r\n");
      out.write("            margin: 0;\r\n");
      out.write("            font-family: 'Nunito Sans', sans-serif;\r\n");
      out.write("            background-color: #f9f9f9;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* Navbar Styling */\r\n");
      out.write("        .navbar {\r\n");
      out.write("            position: fixed;\r\n");
      out.write("            top: 0;\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            height: 90px;\r\n");
      out.write("            background-color: #FF734C;\r\n");
      out.write("            display: flex;\r\n");
      out.write("            justify-content: space-between;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            padding: 0 20px;\r\n");
      out.write("            box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);\r\n");
      out.write("            z-index: 1000;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        h2{\r\n");
      out.write("        	text-align: center;\r\n");
      out.write("        	font-size: 40px;\r\n");
      out.write("        }\r\n");
      out.write("        .navbar-left .nav {\r\n");
      out.write("            display: flex;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .navbar-left {\r\n");
      out.write("            gap: 35px;\r\n");
      out.write("            display: flex;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .app-name {\r\n");
      out.write("            font-size: 28px;\r\n");
      out.write("            font-weight: 700;\r\n");
      out.write("            color: white;\r\n");
      out.write("            margin-right: 20px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        nav {\r\n");
      out.write("            display: flex;\r\n");
      out.write("            gap: 15px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .navbar a {\r\n");
      out.write("            color: white;\r\n");
      out.write("            text-decoration: none;\r\n");
      out.write("            font-size: 18px;\r\n");
      out.write("            font-weight: 600;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .navbar a:hover {\r\n");
      out.write("            color: black;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .user-info {\r\n");
      out.write("            display: flex;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            gap: 15px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .user-info p {\r\n");
      out.write("            margin: 0;\r\n");
      out.write("            color: white;\r\n");
      out.write("            font-size: 18px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .user-info a {\r\n");
      out.write("            color: #fff;\r\n");
      out.write("            padding: 8px 12px;\r\n");
      out.write("            border-radius: 5px;\r\n");
      out.write("            margin-right: 30px;\r\n");
      out.write("            background-color: #ff4500;\r\n");
      out.write("            font-size: 16px;\r\n");
      out.write("            text-decoration: none;\r\n");
      out.write("            transition: background-color 0.3s ease;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .user-info a:hover {\r\n");
      out.write("            background-color: #ff3300;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .cart-button {\r\n");
      out.write("            display: inline-block;\r\n");
      out.write("            margin-right: 30px;\r\n");
      out.write("            padding: 10px 20px;\r\n");
      out.write("            font-size: 18px;\r\n");
      out.write("            font-weight: bold;\r\n");
      out.write("            color: white;\r\n");
      out.write("            background: linear-gradient(90deg, #ff7e5f, #feb47b);\r\n");
      out.write("            border: none;\r\n");
      out.write("            border-radius: 25px;\r\n");
      out.write("            box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);\r\n");
      out.write("            text-decoration: none;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            transition: all 0.3s ease-in-out;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .cart-button:hover {\r\n");
      out.write("            background: linear-gradient(90deg, #feb47b, #ff7e5f);\r\n");
      out.write("            box-shadow: 0 6px 12px rgba(0, 0, 0, 0.2);\r\n");
      out.write("            transform: translateY(-2px);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .cart-button:active {\r\n");
      out.write("            transform: translateY(0);\r\n");
      out.write("            box-shadow: 0 3px 6px rgba(0, 0, 0, 0.1);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* Hamburger Menu */\r\n");
      out.write("        .hamburger {\r\n");
      out.write("            display: none;\r\n");
      out.write("            flex-direction: column;\r\n");
      out.write("            gap: 5px;\r\n");
      out.write("            cursor: pointer;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .hamburger div {\r\n");
      out.write("            width: 25px;\r\n");
      out.write("            height: 3px;\r\n");
      out.write("            background-color: white;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .navbar nav.active {\r\n");
      out.write("            display: flex;\r\n");
      out.write("            flex-direction: column;\r\n");
      out.write("            background-color: #FF734C;\r\n");
      out.write("            position: absolute;\r\n");
      out.write("            top: 70px;\r\n");
      out.write("            left: 0;\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            padding: 10px 0;\r\n");
      out.write("            z-index: 999;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .carousel {\r\n");
      out.write("            max-width: 95%;\r\n");
      out.write("            margin: 50px auto;\r\n");
      out.write("            border-radius: 15px;\r\n");
      out.write("            overflow: hidden;\r\n");
      out.write("            box-shadow: 0 4px 10px rgba(0, 0, 0, 0.1);\r\n");
      out.write("            margin-top: 130px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .carousel-inner img {\r\n");
      out.write("            height: 270px; /* Fixed height for uniformity */\r\n");
      out.write("            object-fit: cover;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .carousel-caption {\r\n");
      out.write("            background: rgba(0, 0, 0, 0.6); /* Semi-transparent background for text */\r\n");
      out.write("            padding: 10px;\r\n");
      out.write("            border-radius: 5px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .carousel-caption h5 {\r\n");
      out.write("            font-size: 20px;\r\n");
      out.write("            font-weight: bold;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .carousel-caption p {\r\n");
      out.write("            font-size: 14px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .container {\r\n");
      out.write("            margin: 50px;\r\n");
      out.write("            margin-top: 30px;\r\n");
      out.write("            display: grid;\r\n");
      out.write("            grid-template-columns: repeat(auto-fit, minmax(250px, 1fr));\r\n");
      out.write("            gap: 50px;\r\n");
      out.write("            padding: 20px;\r\n");
      out.write("        }\r\n");
      out.write("        .container-item {\r\n");
      out.write("            margin: 50px;\r\n");
      out.write("            margin-top: 30px;\r\n");
      out.write("            display: grid;\r\n");
      out.write("            grid-template-columns: repeat(auto-fit, minmax(250px, 1fr));\r\n");
      out.write("            gap: 50px;\r\n");
      out.write("            padding: 20px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .card {\r\n");
      out.write("            border: 1px solid #ddd;\r\n");
      out.write("            border-radius: 10px;\r\n");
      out.write("            margin-bottom: 10px;\r\n");
      out.write("            background-color: #fff;\r\n");
      out.write("            box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);\r\n");
      out.write("            transition: transform 0.3s ease, box-shadow 0.3s ease;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .card:hover {\r\n");
      out.write("            transform: scale(1.05);\r\n");
      out.write("            box-shadow: 0 6px 12px rgba(0, 0, 0, 0.2);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .card img {\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            height: 250px;\r\n");
      out.write("            object-fit: cover;\r\n");
      out.write("            border-radius: 10px 10px 0px 0px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .card-content {\r\n");
      out.write("            padding: 15px;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .card-content h3 {\r\n");
      out.write("            font-size: 1.5rem;\r\n");
      out.write("            color: #1E201E;\r\n");
      out.write("            margin: 10px 0;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .card-content p {\r\n");
      out.write("            font-size: 0.9rem;\r\n");
      out.write("            color: #666;\r\n");
      out.write("            margin: 5px 0;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        a {\r\n");
      out.write("            text-decoration: none;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* Responsive Adjustments */\r\n");
      out.write("        @media (max-width: 790px) {\r\n");
      out.write("            .hamburger {\r\n");
      out.write("                display: flex;\r\n");
      out.write("                width: 10px;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .navbar nav {\r\n");
      out.write("                display: none;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .navbar nav.active {\r\n");
      out.write("                display: flex;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .app-name {\r\n");
      out.write("                font-size: 24px;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .user-info a {\r\n");
      out.write("                font-size: 14px;\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        @media (max-width: 450px) {\r\n");
      out.write("            .hamburger {\r\n");
      out.write("                display: flex;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .navbar nav {\r\n");
      out.write("                display: none;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .navbar nav.active {\r\n");
      out.write("                display: flex;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .app-name {\r\n");
      out.write("                font-size: 20px;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            .user-info a {\r\n");
      out.write("                font-size: 7px;\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("    </style>\r\n");
      out.write("    <script>\r\n");
      out.write("        document.addEventListener('DOMContentLoaded', () => {\r\n");
      out.write("            const hamburger = document.querySelector('.hamburger');\r\n");
      out.write("            const nav = document.querySelector('.navbar nav');\r\n");
      out.write("\r\n");
      out.write("            hamburger.addEventListener('click', () => {\r\n");
      out.write("                nav.classList.toggle('active');\r\n");
      out.write("            });\r\n");
      out.write("        });\r\n");
      out.write("    </script>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("    <!-- Navbar -->\r\n");
      out.write("    <div class=\"navbar\">\r\n");
      out.write("        <div class=\"navbar-left\">\r\n");
      out.write("            <div class=\"title\">\r\n");
      out.write("                <p class=\"app-name\">Food World</p>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"hamburger\">\r\n");
      out.write("                <div></div>\r\n");
      out.write("                <div></div>\r\n");
      out.write("                <div></div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <nav>\r\n");
      out.write("                <a href=\"home.jsp\">Home</a>\r\n");
      out.write("                <a href=\"#restaurant-details\">Restaurants</a>\r\n");
      out.write("                <a href=\"contact.jsp\">Contact Us</a>\r\n");
      out.write("                <a href=\"about.jsp\">About</a>\r\n");
      out.write("            </nav>\r\n");
      out.write("        </div>\r\n");
      out.write("        <a href=\"cart.jsp\" class=\"cart-button\"> Go to Cart</a>\r\n");
      out.write("        <a href=\"ShowOrderHistory\" class=\"cart-button\">OrderHistory</a>\r\n");
      out.write("        <div class=\"user-info\">\r\n");
      out.write("            ");
 
                User user = (User) session.getAttribute("loggedInUser"); 
                if (user != null) { 
            
      out.write("\r\n");
      out.write("                <p>Welcome, ");
      out.print( user.getUsername() );
      out.write("</p>\r\n");
      out.write("                <a href=\"login.jsp\">Logout</a>\r\n");
      out.write("            ");
 
                } else { 
            
      out.write("\r\n");
      out.write("                <a href=\"login.jsp\">Login</a>\r\n");
      out.write("                <a href=\"register.jsp\">Register</a>\r\n");
      out.write("            ");
 
                } 
            
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("    <div id=\"carouselExampleCaptions\" class=\"carousel slide\" data-bs-ride=\"carousel\">\r\n");
      out.write("    <div class=\"carousel-indicators\">\r\n");
      out.write("        <button type=\"button\" data-bs-target=\"#carouselExampleCaptions\" data-bs-slide-to=\"0\" class=\"active\" aria-current=\"true\" aria-label=\"Slide 1\"></button>\r\n");
      out.write("        <button type=\"button\" data-bs-target=\"#carouselExampleCaptions\" data-bs-slide-to=\"1\" aria-label=\"Slide 2\"></button>\r\n");
      out.write("        <button type=\"button\" data-bs-target=\"#carouselExampleCaptions\" data-bs-slide-to=\"2\" aria-label=\"Slide 3\"></button>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"carousel-inner\">\r\n");
      out.write("        <div class=\"carousel-item active\">\r\n");
      out.write("            <img src=\"https://images.pexels.com/photos/958545/pexels-photo-958545.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1\" class=\"d-block w-100\" alt=\"First slide\">\r\n");
      out.write("            <div class=\"carousel-caption d-none d-md-block\">\r\n");
      out.write("                <h5>Eat Tastier</h5>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"carousel-item\">\r\n");
      out.write("            <img src=\"https://images.freeimages.com/images/large-previews/ac6/roasted-chicken-feast-0410-5702617.jpg\" class=\"d-block w-100\" alt=\"Second slide\">\r\n");
      out.write("            <div class=\"carousel-caption d-none d-md-block\">\r\n");
      out.write("                <h5>Stay Healthier</h5>\r\n");
      out.write("               \r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"carousel-item\">\r\n");
      out.write("            <img src=\"https://cdn.pixabay.com/photo/2014/04/22/02/56/pizza-329523_1280.jpg\" class=\"d-block w-100\" alt=\"Third slide\">\r\n");
      out.write("            <div class=\"carousel-caption d-none d-md-block\">\r\n");
      out.write("                <h5>Become Happier</h5>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <button class=\"carousel-control-prev\" type=\"button\" data-bs-target=\"#carouselExampleCaptions\" data-bs-slide=\"prev\">\r\n");
      out.write("        <span class=\"carousel-control-prev-icon\" aria-hidden=\"true\"></span>\r\n");
      out.write("        <span class=\"visually-hidden\">Previous</span>\r\n");
      out.write("    </button>\r\n");
      out.write("    <button class=\"carousel-control-next\" type=\"button\" data-bs-target=\"#carouselExampleCaptions\" data-bs-slide=\"next\">\r\n");
      out.write("        <span class=\"carousel-control-next-icon\" aria-hidden=\"true\"></span>\r\n");
      out.write("        <span class=\"visually-hidden\">Next</span>\r\n");
      out.write("    </button>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<script src=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.6.0/js/fontawesome.min.js\" integrity=\"sha512-NeFv3hB6XGV+0y96NVxoWIkhrs1eC3KXBJ9OJiTFktvbzJ/0Kk7Rmm9hJ2/c2wJjy6wG0a0lIgehHjCTDLRwWw==\" crossorigin=\"anonymous\" referrerpolicy=\"no-referrer\"></script>\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js\" integrity=\"sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("    \r\n");
      out.write("    <div class = \"popular-items\">\r\n");
      out.write("    	<h2>Popular Items</h2>\r\n");
      out.write("    	<div class=\"container-item\">\r\n");
      out.write("        ");
 
            List<Menu> hmList = (List<Menu>) session.getAttribute("hmList");
            if (hmList != null) {
                for (Menu res : hmList) {
        
      out.write("\r\n");
      out.write("        <a href=\"ShowMenu?restaurantId=");
      out.print( res.getRestaurantId() );
      out.write("\">\r\n");
      out.write("        <div class=\"card\">\r\n");
      out.write("            <img src=\"");
      out.print( res.getImage() );
      out.write("\" alt=\"Restaurant\">\r\n");
      out.write("            <div class=\"card-content\">\r\n");
      out.write("                <h3>");
      out.print( res.getName() );
      out.write("</h3>\r\n");
      out.write("                <p><strong>Cuisine:</strong> ");
      out.print( res.getPrice() );
      out.write("</p>\r\n");
      out.write("                <p><strong>Location:</strong> ");
      out.print( res.getRating() );
      out.write("</p>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        </a>\r\n");
      out.write("        ");
 
            } 
        } 
        
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("    	\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("    <!-- Restaurant Cards -->\r\n");
      out.write("    <div id = \"restaurant-details\">\r\n");
      out.write("    	<h2>Restaurants</h2>\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("    <!-- <h2>Restaurants</h2> -->\r\n");
      out.write("        ");
 
            List<Restaurant> resList = (List<Restaurant>) session.getAttribute("resList");
            if (resList != null) {
                for (Restaurant res : resList) {
        
      out.write("\r\n");
      out.write("        <a href=\"ShowMenu?restaurantId=");
      out.print( res.getRestaurantId() );
      out.write("\">\r\n");
      out.write("        <div class=\"card\">\r\n");
      out.write("            <img src=\"");
      out.print( res.getImage() );
      out.write("\" alt=\"Restaurant\">\r\n");
      out.write("            <div class=\"card-content\">\r\n");
      out.write("                <h3>");
      out.print( res.getName() );
      out.write("</h3>\r\n");
      out.write("                <p><strong>Cuisine:</strong> ");
      out.print( res.getCuisineType() );
      out.write("</p>\r\n");
      out.write("                <p><strong>Location:</strong> ");
      out.print( res.getAddress() );
      out.write("</p>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        </a>\r\n");
      out.write("        ");
 
            } 
        } 
        
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
